### ISSUE TITLE
The modal is not working on the latest Chrome and Firefox

### ISSUE THREAD

**Issue by whileLooper** [shlomiassaf/angular2-modal#135]
IMPORTANT: Please provide a sample using http://plnkr.co/edit/iiQett?p=preview 

* **I'm submitting a ...**
[X ] bug report

* **Do you want to request a *feature* or report a *bug*?**
After I upgrade my Chrome into latest version which is Version 52.0.2743.82 (64-bit), the bootstrap modal plugin stop working, even on the web site home page demos.
But I tested it on Safari, it works fine on Safari, not on Chrome and Firefox.

* **What is the current behavior?**
Here are the errors in the page:
`EXCEPTION: Error in ./BSModalContainer class BSModalContainer - inline template:3:10`

`ORIGINAL EXCEPTION: TypeError: Failed to execute 'animate' on 'Element': 'null' is not a valid value for easing`

`platform-browser.umd.js:1900 TypeError: Failed to execute 'animate' on 'Element': 'null' is not a valid value for easing
    at TypeError (native)
    at WebAnimationsDriver._triggerWebAnimation (http://shlomiassaf.github.io/angular2-modal/vendor/@angular/platform-browser/bundles/platform-browser.umd.js:1693:24)
    at WebAnimationsDriver.animate (http://shlomiassaf.github.io/angular2-modal/vendor/@angular/platform-browser/bundles/platform-browser.umd.js:1688:31)
    at DomRenderer.animate (http://shlomiassaf.github.io/angular2-modal/vendor/@angular/platform-browser/bundles/platform-browser.umd.js:2618:42)
    at DebugDomRenderer.animate (http://shlomiassaf.github.io/angular2-modal/vendor/@angular/core/bundles/core.umd.js:11743:35)
    at BSModalContainer_fade_0_factory (BSModalContainer.template.js:26:19)
    at DebugAppView._View_BSModalContainer0.detectChangesInternal (BSModalContainer.template.js:165:5)
    at DebugAppView.AppView.detectChanges (http://shlomiassaf.github.io/angular2-modal/vendor/@angular/core/bundles/core.umd.js:12143:18)
    at DebugAppView.detectChanges (http://shlomiassaf.github.io/angular2-modal/vendor/@angular/core/bundles/core.umd.js:12247:48)
    at DebugAppView.AppView.detectViewChildrenChanges (http://shlomiassaf.github.io/angular2-modal/vendor/@angular/core/bundles/core.umd.js:12169:23)`

![screen shot 2016-07-25 at 3 11 07 pm](https://cloud.githubusercontent.com/assets/3445170/17113674/c20c803e-5279-11e6-8347-9e407dfcc98b.png)

**Comment by shlomiassaf** [comment]
Hi,

This is an angular bug and it will be fixed when RC.5 is out.
See angular/angular#9780

**Comment by ellern** [comment]
Any known workaround until RC 5 is out?

**Comment by shlomiassaf** [comment]
@ellern Basically it's fixed in the current master, I will update the package in npm.

**Comment by shlomiassaf** [comment]
@ellern @whileLooper try version 1.0.9

**Comment by ellern** [comment]
Just updated to 1.0.9, and no problems so far.

**Comment by whileLooper** [comment]
thanks for the solution, @shlomiassaf
