### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by rolandoldengarm** [shlomiassaf/angular2-modal#138]
I've just updated to RC4 and the latest version of angular2-modal, and now on component load I get the following error. Everything used to work before. I'm using angular-cli. Any help please?
````
zone.js:461 Unhandled Promise rejection: (SystemJS) Cannot read property 'prototype' of undefined
	TypeError: Cannot read property 'prototype' of undefined
	    at __extends (http://localhost:4200/vendor/angular2-modal/platform-browser/outside-event-plugin.js:7:68)
	    at eval (http://localhost:4200/vendor/angular2-modal/platform-browser/outside-event-plugin.js:47:5)
	    at Object.eval (http://localhost:4200/vendor/angular2-modal/platform-browser/outside-event-plugin.js:96:2)
	    at eval (http://localhost:4200/vendor/angular2-modal/platform-browser/outside-event-plugin.js:99:4)
	    at eval (http://localhost:4200/vendor/angular2-modal/platform-browser/outside-event-plugin.js:100:3)
	Evaluating http://localhost:4200/vendor/angular2-modal/platform-browser/outside-event-plugin.js
	Evaluating http://localhost:4200/vendor/angular2-modal/platform-browser/index.js
	Evaluating http://localhost:4200/main.js
	Error loading http://localhost:4200/main.js ; Zone: <root> ; Task: Promise.then ; Value: Error: (SystemJS) Cannot read property 'prototype' of undefined(…)
````

**Comment by rolandoldengarm** [comment]
Ah cleared node_modules and dist folder, and it's working :dancer:
