### ISSUE TITLE
Modal not closing Angular 2 version 2.0 + Angular Cli beta 15

### ISSUE THREAD

**Issue by sudhishsasi** [shlomiassaf/angular2-modal#208]
This was working fine in Angular RC4 and Angular Cli beta 10, after upgrading to Angular 2 version 2.0 + Angular Cli beta 15 modal pop is not closing and getting the below error. issue : https://github.com/shlomiassaf/angular2-modal/issues/188 doesn't seems to be fixed.

EXCEPTION: Uncaught (in promise): undefined main.bundle.js:40494
ORIGINAL STACKTRACE: main.bundle.js:40499
Error: Uncaught (in promise): undefined
    at resolvePromise (http://localhost:4200/main.bundle.js:71961:31)
    at PromiseCompleter.reject (http://localhost:4200/main.bundle.js:71938:13)
    at http://localhost:4200/main.bundle.js:62135:27
    at ZoneDelegate.invokeTask (http://localhost:4200/main.bundle.js:71768:37)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (http://localhost:4200/main.bundle.js:58242:37)
    at ZoneDelegate.invokeTask (http://localhost:4200/main.bundle.js:71767:42)
    at Zone.runTask (http://localhost:4200/main.bundle.js:71668:47)
    at ZoneTask.invoke (http://localhost:4200/main.bundle.js:71836:33) main.bundle.js:40500
Error {stack: "Error: Uncaught (in promise): undefined↵    at res…e (http://localhost:4200/main.bundle.js:71836:33)", rejection: undefined, promise: ZoneAwarePromise, zone: Zone, task: ZoneTask…}

-

**Comment by shlomiassaf** [comment]
#208 fixed, not released yet.

**Comment by naveenprincep** [comment]
Same issue. Its working fine in normal demo application but when it used this inside Angular-Cli beta 15, I am getting error when closing modal.

EXCEPTION: Uncaught (in promise): undefined
    ErrorHandler.handleError @ main.bundle.js:41669
ORIGINAL STACKTRACE:
    ErrorHandler.handleError @ main.bundle.js:41674
Error: Uncaught (in promise): undefined
    at resolvePromise (main.bundle.js:76595)
    at PromiseCompleter.reject (main.bundle.js:76572)
    at main.bundle.js:64988
    at ZoneDelegate.invokeTask (main.bundle.js:76402)
    at Object.onInvokeTask (main.bundle.js:61286)
    at ZoneDelegate.invokeTask (main.bundle.js:76401)
    at Zone.runTask (main.bundle.js:76302)
    at ZoneTask.invoke (main.bundle.js:76470)
    ErrorHandler.handleError @ main.bundle.js:41675
Error: Uncaught (in promise): undefined(…)
    consoleError @ main.bundle.js:76523

I tried #188 but its not fixing the issue. Maybe I am missing something. When will you release the next version?

**Comment by shlomiassaf** [comment]
@naveenprincep It should be released this week with AoT support for the CLI.
I hope it will go smooth :)

**Comment by naveenprincep** [comment]
@shlomiassaf  Thanks for the fast release. I updated to new version but I am getting an error while initial loading

Uncaught SyntaxError: Unexpected identifier

**Comment by sudhishsasi** [comment]
Issue still exist in Angular cli beta 15 and 16.

**Comment by shlomiassaf** [comment]
I need to check that...

The new version now comes in 2 versions (in the same package)
 - ES5 1 file bundle UMD
 - ES6 modular version

I guess you'r setup is having issue dealing with the ES6 version, I need to check why.

If you are not using a module bundler that support ES6 imports it will automatically resolve to the UMD so you'r setup supports that but can't parse the file.

**Comment by naveenprincep** [comment]
Thanks. Now its building but getting the issue mentioned in #188

**Comment by naveenprincep** [comment]
#223  seems to fix the issue. Thanks
