### ISSUE TITLE
webpack -p build error

### ISSUE THREAD

**Issue by shotleybuilder** [shlomiassaf/angular2-modal#25]
Possibly this [https://github.com/palantir/tslint/pull/687](url)

The local install seems broken on many levels just now (?)

```
jason@jason-LIFEBOOK-AH532:~/Desktop/angular2-modal$ webpack
Hash: b11bc454943a34bd84db
Version: webpack 1.12.14
Time: 536ms
     Asset      Size  Chunks             Chunk Names
 vendor.js  55 bytes    0, 1  [emitted]  vendor
 common.js   3.56 kB    1, 0  [emitted]  common
vendor.map  86 bytes    0, 1  [emitted]  vendor
common.map   3.57 kB    1, 0  [emitted]  common
    + 3 hidden modules

ERROR in ./src/demo/vendor.ts
Module build failed: Error: Could not find the following rules specified in the configuration:
no-trailing-comma
    at Object.loadRules (/home/jason/Desktop/angular2-modal/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/home/jason/Desktop/angular2-modal/node_modules/tslint/lib/tslint.js:24:44)
    at Object.lint (/home/jason/Desktop/angular2-modal/node_modules/tslint-loader/index.js:55:23)
    at Object.module.exports (/home/jason/Desktop/angular2-modal/node_modules/tslint-loader/index.js:139:8)

ERROR in ./src/angular2-modal/angular2-modal.ts
Module build failed: Error: Could not find the following rules specified in the configuration:
no-trailing-comma
    at Object.loadRules (/home/jason/Desktop/angular2-modal/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/home/jason/Desktop/angular2-modal/node_modules/tslint/lib/tslint.js:24:44)
    at Object.lint (/home/jason/Desktop/angular2-modal/node_modules/tslint-loader/index.js:55:23)
    at Object.module.exports (/home/jason/Desktop/angular2-modal/node_modules/tslint-loader/index.js:139:8)

ERROR in ./src/demo/bootstrap.ts
Module build failed: Error: Could not find the following rules specified in the configuration:
no-trailing-comma
    at Object.loadRules (/home/jason/Desktop/angular2-modal/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/home/jason/Desktop/angular2-modal/node_modules/tslint/lib/tslint.js:24:44)
    at Object.lint (/home/jason/Desktop/angular2-modal/node_modules/tslint-loader/index.js:55:23)
    at Object.module.exports (/home/jason/Desktop/angular2-modal/node_modules/tslint-loader/index.js:139:8)
```

**Comment by shlomiassaf** [comment]
Fixed

**Comment by aaroncalderon** [comment]
How was this fixed?
