### ISSUE TITLE
Opening and closing modals causes JS errors on Angular2 RC-1

### ISSUE THREAD

**Issue by franksrevenge** [shlomiassaf/angular2-modal#98]
I'm experiencing errors when showing and hiding modals using Angular2 RC-1 and Angular2-modal 1.0.0.

Any thoughts on what am I doing wrong? (Code below)

When the modal is shown, the following error is registered. The modal still shows up, though:

```
Uncaught TypeError: Cannot read property 'onAndCancel' of null
onceOnOutside @ outside-event-plugin.js:63
(anonymous function) @ outside-event-plugin.js:77
ZoneDelegate.invokeTask @ zone.js:356
Zone.runTask @ zone.js:256
ZoneTask.invoke @ zone.js:423
```

When the modal is dismissed, I see another set of errors. The modal does disappear.

```
platform-browser.umd.js:971 EXCEPTION: Error in ./BSMessageModal class BSMessageModal - inline template:8:4

platform-browser.umd.js:962 EXCEPTION: Error in ./BSMessageModal class BSMessageModal - inline template:8:4
BrowserDomAdapter.logError @ platform-browser.umd.js:962
BrowserDomAdapter.logGroup @ platform-browser.umd.js:972
ExceptionHandler.call @ core.umd.js:3696
(anonymous function) @ core.umd.js:8951
schedulerFn @ core.umd.js:6007
SafeSubscriber.__tryOrUnsub @ Subscriber.js:225
SafeSubscriber.next @ Subscriber.js:174
Subscriber._next @ Subscriber.js:124
Subscriber.next @ Subscriber.js:88
Subject._finalNext @ Subject.js:128
Subject._next @ Subject.js:120
Subject.next @ Subject.js:77
EventEmitter.emit @ core.umd.js:5996
NgZone._zoneImpl.NgZoneImpl.onError @ core.umd.js:6227
NgZoneImpl.inner.inner.fork.onHandleError @ core.umd.js:6096
ZoneDelegate.handleError @ zone.js:327
Zone.runTask @ zone.js:259
ZoneTask.invoke @ zone.js:423
platform-browser.umd.js:962

ORIGINAL EXCEPTION: TypeError: fn is not a functionBrowserDomAdapter.logError @ platform-browser.umd.js:962
ExceptionHandler.call @ core.umd.js:3705
(anonymous function) @ core.umd.js:8951
schedulerFn @ core.umd.js:6007
SafeSubscriber.__tryOrUnsub @ Subscriber.js:225
SafeSubscriber.next @ Subscriber.js:174
Subscriber._next @ Subscriber.js:124
Subscriber.next @ Subscriber.js:88
Subject._finalNext @ Subject.js:128
Subject._next @ Subject.js:120
Subject.next @ Subject.js:77
EventEmitter.emit @ core.umd.js:5996
NgZone._zoneImpl.NgZoneImpl.onError @ core.umd.js:6227
NgZoneImpl.inner.inner.fork.onHandleError @ core.umd.js:6096
ZoneDelegate.handleError @ zone.js:327
Zone.runTask @ zone.js:259
ZoneTask.invoke @ zone.js:423
platform-browser.umd.js:962

ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ platform-browser.umd.js:962
ExceptionHandler.call @ core.umd.js:3708
(anonymous function) @ core.umd.js:8951
schedulerFn @ core.umd.js:6007
SafeSubscriber.__tryOrUnsub @ Subscriber.js:225
SafeSubscriber.next @ Subscriber.js:174
Subscriber._next @ Subscriber.js:124
Subscriber.next @ Subscriber.js:88
Subject._finalNext @ Subject.js:128
Subject._next @ Subject.js:120
Subject.next @ Subject.js:77
EventEmitter.emit @ core.umd.js:5996
NgZone._zoneImpl.NgZoneImpl.onError @ core.umd.js:6227
NgZoneImpl.inner.inner.fork.onHandleError @ core.umd.js:6096
ZoneDelegate.handleError @ zone.js:327
Zone.runTask @ zone.js:259
ZoneTask.invoke @ zone.js:423

platform-browser.umd.js:962 TypeError: fn is not a function
    at Array.eval (outside-event-plugin.js:78)
    at DebugAppView.AppView.destroyLocal (core.umd.js:9935)
    at DebugAppView.destroyLocal (core.umd.js:10074)
    at DebugAppView.AppView._destroyRecurse (core.umd.js:9929)
    at DebugAppView.AppView._destroyRecurse (core.umd.js:9927)
    at DebugAppView.AppView._destroyRecurse (core.umd.js:9927)
    at DebugAppView.AppView.destroy (core.umd.js:9915)
    at ComponentRef_.destroy (core.umd.js:8635)
    at DialogRef.dialog.destroy (dom-modal-renderer.js:33)
    at DialogRef.dismiss (dialog-ref.js:42)BrowserDomAdapter.logError @ platform-browser.umd.js:962

ExceptionHandler.call @ core.umd.js:3709
(anonymous function) @ core.umd.js:8951
schedulerFn @ core.umd.js:6007
SafeSubscriber.__tryOrUnsub @ Subscriber.js:225
SafeSubscriber.next @ Subscriber.js:174
Subscriber._next @ Subscriber.js:124
Subscriber.next @ Subscriber.js:88
Subject._finalNext @ Subject.js:128
Subject._next @ Subject.js:120
Subject.next @ Subject.js:77
EventEmitter.emit @ core.umd.js:5996
NgZone._zoneImpl.NgZoneImpl.onError @ core.umd.js:6227
NgZoneImpl.inner.inner.fork.onHandleError @ core.umd.js:6096
ZoneDelegate.handleError @ zone.js:327
Zone.runTask @ zone.js:259
ZoneTask.invoke @ zone.js:423
platform-browser.umd.js:962

ERROR CONTEXT:BrowserDomAdapter.logError @ platform-browser.umd.js:962
ExceptionHandler.call @ core.umd.js:3712
(anonymous function) @ core.umd.js:8951
schedulerFn @ core.umd.js:6007
SafeSubscriber.__tryOrUnsub @ Subscriber.js:225
SafeSubscriber.next @ Subscriber.js:174
Subscriber._next @ Subscriber.js:124
Subscriber.next @ Subscriber.js:88
Subject._finalNext @ Subject.js:128
Subject._next @ Subject.js:120
Subject.next @ Subject.js:77
EventEmitter.emit @ core.umd.js:5996
NgZone._zoneImpl.NgZoneImpl.onError @ core.umd.js:6227
NgZoneImpl.inner.inner.fork.onHandleError @ core.umd.js:6096
ZoneDelegate.handleError @ zone.js:327
Zone.runTask @ zone.js:259
ZoneTask.invoke @ zone.js:423
platform-browser.umd.js:962 DebugContext {_view: _View_BSMessageModal0, _nodeIndex: 9, _tplRow: 8, _tplCol: 4}
BrowserDomAdapter.logError @ platform-browser.umd.js:962
ExceptionHandler.call @ core.umd.js:3713
(anonymous function) @ core.umd.js:8951
schedulerFn @ core.umd.js:6007
SafeSubscriber.__tryOrUnsub @ Subscriber.js:225
SafeSubscriber.next @ Subscriber.js:174
Subscriber._next @ Subscriber.js:124
Subscriber.next @ Subscriber.js:88
Subject._finalNext @ Subject.js:128
Subject._next @ Subject.js:120
Subject.next @ Subject.js:77
EventEmitter.emit @ core.umd.js:5996
NgZone._zoneImpl.NgZoneImpl.onError @ core.umd.js:6227
NgZoneImpl.inner.inner.fork.onHandleError @ core.umd.js:6096
ZoneDelegate.handleError @ zone.js:327
Zone.runTask @ zone.js:259
ZoneTask.invoke @ zone.js:423
Subscriber.js:229 

Uncaught EXCEPTION: Error in ./BSMessageModal class BSMessageModal - inline template:8:4
ORIGINAL EXCEPTION: TypeError: fn is not a function
ORIGINAL STACKTRACE:
TypeError: fn is not a function
    at Array.eval (http://localhost:63342/auth-web-client/node_modules/angular2-modal/platform-browser/outside-event-plugin.js:78:41)
    at DebugAppView.AppView.destroyLocal (http://localhost:63342/auth-web-client/node_modules/@angular/core/core.umd.js:9935:36)
    at DebugAppView.destroyLocal (http://localhost:63342/auth-web-client/node_modules/@angular/core/core.umd.js:10074:47)
    at DebugAppView.AppView._destroyRecurse (http://localhost:63342/auth-web-client/node_modules/@angular/core/core.umd.js:9929:18)
    at DebugAppView.AppView._destroyRecurse (http://localhost:63342/auth-web-client/node_modules/@angular/core/core.umd.js:9927:29)
    at DebugAppView.AppView._destroyRecurse (http://localhost:63342/auth-web-client/node_modules/@angular/core/core.umd.js:9927:29)
    at DebugAppView.AppView.destroy (http://localhost:63342/auth-web-client/node_modules/@angular/core/core.umd.js:9915:18)
    at ComponentRef_.destroy (http://localhost:63342/auth-web-client/node_modules/@angular/core/core.umd.js:8635:86)
    at DialogRef.dialog.destroy (http://localhost:63342/auth-web-client/node_modules/angular2-modal/providers/dom-modal-renderer.js:33:58)
    at DialogRef.dismiss (http://localhost:63342/auth-web-client/node_modules/angular2-modal/models/dialog-ref.js:42:14)

ERROR CONTEXT:
[object Object]SafeSubscriber.__tryOrUnsub @ Subscriber.js:229
SafeSubscriber.next @ Subscriber.js:174
Subscriber._next @ Subscriber.js:124
Subscriber.next @ Subscriber.js:88
Subject._finalNext @ Subject.js:128
Subject._next @ Subject.js:120
Subject.next @ Subject.js:77
EventEmitter.emit @ core.umd.js:5996
NgZone._zoneImpl.NgZoneImpl.onError @ core.umd.js:6227
NgZoneImpl.inner.inner.fork.onHandleError @ core.umd.js:6096
ZoneDelegate.handleError @ zone.js:327
Zone.runTask @ zone.js:259
ZoneTask.invoke @ zone.js:423
```

Abbreviated code:

```ts
import {Component, ViewContainerRef} from '@angular/core';
import {Modal, BS_MODAL_PROVIDERS} from 'angular2-modal/plugins/bootstrap/index';

@Component(
	{
		templateUrl : 'app/components/user/user-view.component.html',
		directives: [ ROUTER_DIRECTIVES ],
		providers : [],
		viewProviders : [ ...BS_MODAL_PROVIDERS ]
	}
)

export class UserViewComponent implements OnActivate
{
	constructor(
		private viewContainer: ViewContainerRef
	)
	{
		modal.defaultViewContainer = viewContainer;
	}

	onClick()
	{
		var title = 'Hello';
		var message = 'world';

		return this.modal.confirm()
			.size( 'lg' )
			.isBlocking( true )
			.keyboard( 27 )
			.title( title )
			.body( message )
			.open()
			.then(
				function( d )
				{
					// ...
				}
			);
	}
}
```

**Comment by mmurphy7** [comment]
I was having this same issue. It appears to be caused by setting isBlocking to true. For now I have set all of my modals to isBlocking = false and am no longer seeing any issues.

**Comment by jamesjrg** [comment]
Same problem here, only happened after updating to RC1. I think the problem is in platform-browser/outside-event-plugin.js, on this line:

`var onceOnOutside = function () { return _this._DOM.onAndCancel(_this._DOM.getGlobalEventTarget('document'), eventMap[eventName], bubbleNonAncestorHandlerFactory(element, function (evt) { return zone.runGuarded(function () { return handler(evt); }); })); };`

Seems this._DOM is now null in this context. I don't know what needs changing to make it work with the latest version of Angular.

**Comment by jamesjrg** [comment]
After some googling there are several people facing similar-sounding issues regarding Angular 2, TypeScript, DOM adapters, and the abstracted DOM being null:

https://github.com/angular/angular/issues/6904
http://stackoverflow.com/questions/35799022/angular-2-dom-adapter
https://medium.com/@TheLarkInn/creating-custom-dom-events-in-angular2-f326d348dc8b#.wdlcnpt78

There are various workarounds suggested, though all would involve modifying the outside-event-plugin code

**Comment by jamesjrg** [comment]
One of those issues linked above then links back to an issue reported in angular 2 modal, which was then closed:

https://github.com/shlomiassaf/angular2-modal/issues/44

Using the info there I made the modal work again by adding the following immediately before the call to bootstrap(...):

```
import {BrowserDomAdapter} from '@angular/platform-browser/src/browser/browser_adapter';
BrowserDomAdapter.makeCurrent();
```

However I'm a bit confused - the comment regarding makeCurrent in the above issue is from the author of angular 2 modal, so I assume that this isn't meant to be necessary for normal use.

**Comment by shlomiassaf** [comment]
Removed dep on getDOM(), this should not be an issue now.
